### ISSUE TITLE
404 on authorize

### ISSUE THREAD

**Issue by sweetcoco** [thegameofcode/fitbit-client-oauth2#2]
looks like fitbit's OAuth 2.0: Authorization URI is: https://www.fitbit.com/oauth2/authorize

the config file here sets the base url to:

```
const FITBIT_BASE_API_URL = 'https://api.fitbit.com';
```

causing a 404 when attempting to authorize.

**Comment by guumaster** [comment]
They've changed it to the new url. I'll update it soon, or accept a PR.
