### ISSUE TITLE
Issue with refreshing tokens?

### ISSUE THREAD

**Issue by sweetcoco** [thegameofcode/fitbit-client-oauth2#4]
This could entirely be my own fault, as I think I'm doing something wrong, but after reading through the src/auth.js file I've been implementing my refresh like:

```
var fitbitTokens = {
                    access_token: user.access_token,
                    refresh_token: user.refresh_token,
                    expires_in: 3600
                };

client.refreshAccessToken(fitbitTokens)
     .then(function (new_token) {
                    // save new_token.access_token
                    // save new_token.refresh_token
                    // save new_token.expires_in
                    // save new_token.expires_at
     }).catch(function(err) {
                    console.log('error refreshing user token', err);
     });

```

The problem is... it doesn't actually refresh! new_token comes back with the same access_token as before, and that could be as intended but I get a 401 error back from fitbit because the refresh isn't actually successful. Any thoughts?

Is there something else I should be doing with new_token instead of just saving new_token.access_token, new_token.refresh_token, new_token.expires_in, and new_token.expires_at to my db?

**Comment by ghost** [comment]
The `refreshToken` method have an option parameter where you can force a refresh. What could be happening is that it is deciding NOT to make the call an resolve the promise with the same tokens. 

Try this: 

``` js
client.refreshAccessToken(fitbitTokens, {forceRefresh: true}).then(.....)
```

**Comment by sweetcoco** [comment]
Works like a charm! It was resolving with the same token. I'll just make my own check to make sure the token isn't expired, that way the force refresh only happens when it needs to. Thanks!

**Comment by guumaster** [comment]
You may also check that, but that is what the code does. If the token is not expired return the same unless you forced it. Isn't that working for you?

**Comment by sweetcoco** [comment]
I'm not sure if that's working or not. I've had my own check in place since the beginning. I can see that's what the code is supposed to do, and it probably does, but how does it know if your token is expired or not? seems like expires_at should be required with the refreshAccessToken if you want that functionality? It's possible I wasn't sending that info with the tokens earlier.

**Comment by guumaster** [comment]
That may be the reason. expires_at is not mandatory, but is used to check expiration. Ok, I'll close it then.
