### ISSUE TITLE
url to fitbit confused

### ISSUE THREAD

**Issue by keneasson** [thegameofcode/fitbit-client-oauth2#5]
since the update, doing an intraday time series request the api points me to the wrong url:
options: 
   { url: 'https://fitbit.com/1/user/-/activities/steps/date/today/today/15min.json',
     method: 'GET',
     json: true,

</html>]
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - \r\n\r\n<!DOCTYPE html PUBLIC

Was there something else that changed that didn't get pushed into the 2.0.1 release?
  "name": "fitbit-client-oauth2",
  "version": "2.0.1",
  "description": "A fitbit client using OAuth 2.0 authentication.",

thanks for any help

**Comment by keneasson** [comment]
modifying src/config.js resolved my issues: 
const FITBIT_BASE_API_URL = 'https://api.fitbit.com';

The fitbit website now shows this to be the url for requests:
https://dev.fitbit.com/docs/activity/
Resource URL
GET https://api.fitbitcom/1/user/[user-id]/activities/date/[date].json

**Comment by ghost** [comment]
They are moving around URLs, that's why we published 2.0.1. I'll update ASAP. or accept a PR :)
