### ISSUE TITLE
buildIntradayTimeSeriesOptions {extra} not being replaced

### ISSUE THREAD

**Issue by keneasson** [thegameofcode/fitbit-client-oauth2#7]
in line 73 of src/helpers.js buildIntradayTimeSeriesOptions() doesn't add startTime, endTime if set in options.

patch:
--    url.replace('{extra}', extra);
++    url = url.replace('{extra}', extra);

**Comment by ghost** [comment]
you are just two clicks away of PR :+1:

**Comment by guumaster** [comment]
solved with PR #8 .
